version: "3.9"
networks:
  default:
    name: todo_api
services:
  db:
    image: "postgres"
    restart: always
    environment:
      POSTGRES_USER: todo_api_rw
      POSTGRES_PASSWORD: hello_rust
      POSTGRES_DB: todo_api
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U todo_api_rw -d todo_api" ]
      interval: 5s
      timeout: 5s
      retries: 5
  todo_api:
    depends_on:
      db:
        condition: service_healthy
    image: todo-api-rust:local
    container_name: todo_api_rust_local 
    build:
      context: .
      dockerfile: Api.DockerFile
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=postgres://todo_api_rw:hello_rust@db/todo_api
      - RUST_LOG=debug #optional
      - RUST_BACKTRACE=1 #optional
